apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    app.kubernetes.io/name: media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hcloud-mass-storage
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-server.default.svc.cluster.local/share##
    volumeAttributes:
      source: "//u358944-sub1.your-storagebox.de/u358944-sub1"
    nodeStageSecretRef:
      name: smb-secrets
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  resources:
    requests:
      storage: 1Ti
  storageClassName: hcloud-mass-storage
  volumeName: media-pv
  accessModes:
    - ReadWriteMany