---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-media-proxy
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-media-proxy
  namespace: media
rules:
  - apiGroups: [""]  # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""]  # "" indicates the core API group
    resourceNames: ["tailscale-auth"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-media-proxy
  namespace: media
subjects:
  - kind: ServiceAccount
    name: tailscale-proxy
roleRef:
  kind: Role
  name: tailscale-proxy
  apiGroup: rbac.authorization.k8s.io
