---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-monitoring-kiali
  namespace: flux-system
spec:
  path: ./clusters/hetzner/apps/monitoring/kiali/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 6h0s
  timeout: 30m
