apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smb-csi
  namespace: kube-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  timeout: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.11.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb-charts
        namespace: flux-system
  interval: 6h