apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smb-secrets
  namespace: kube-system
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: kv/services/smb
        property: username
    - secretKey: password
      remoteRef:
        key: kv/services/smb
        property: password