apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-mass-storage
provisioner: smb.csi.k8s.io
parameters:
  source: "//u358944-sub1.your-storagebox.de/u358944-sub1"
  csi.storage.k8s.io/node-stage-secret-name: "smb-secrets"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001