apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media
  labels:
    app.kubernetes.io/name: jackett
spec:
  selector:
    app.kubernetes.io/name: jackett
  ports:
  - targetPort: http
    port: 80
