apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: jackett
  name: jackett
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  serviceName: "jackett"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      hostname: jackett
      serviceAccountName: tailscale
      containers:
        - name: jackett
          image: ghcr.io/linuxserver/jackett:0.21.481
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 9117
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce