apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: jackett
  name: jackett
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  serviceName: "jackett"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
    spec:
      hostname: jackett
      containers:
        - name: jackett
          image: ghcr.io/linuxserver/jackett:0.21.481
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 9117
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
          env:
            - name: DOCKER_MODS
              value: ghcr.io/behnh/docker-mod:main
            - name: TAILSCALE_STATE_DIR
              value: /config/tailscale
            - name: TAILSCALE_SERVE_MODE
              value: "https"
            - name: TAILSCALE_SERVE_PORT
              value: "9117"
            - name: TAILSCALE_HOSTNAME
              value: "jackett"
            - name: TAILSCALE_CUSTOM_SERVER
              value: "https://vpn.behn.dev"
          envFrom:
            - secretRef:
                name: ts-jackett
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce