apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  resources:
    requests:
      storage: 1Ti
  storageClassName: hcloud-mass-storage
  accessModes:
    - ReadWriteMany
