apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: sabnzbd
    sidecar.istio.io/inject: "false"
  name: sabnzbd
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  serviceName: "sabnzbd"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      hostname: sabnzbd
      containers:
        - name: sabnzbd
          image: ghcr.io/linuxserver/sabnzbd:4.0.3
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: incomplete-downloads
              mountPath: /incomplete-downloads
          env:
            - name: DOCKER_MODS
              value: ghcr.io/behnh/docker-mod:main
            - name: TAILSCALE_STATE_DIR
              value: /config/tailscale
            - name: TAILSCALE_SERVE_MODE
              value: "http"
            - name: TAILSCALE_SERVE_PORT
              value: "8080"
            - name: TAILSCALE_HOSTNAME
              value: "sabnzbd"
            - name: TAILSCALE_CUSTOM_SERVER
              value: "https://vpn.behn.dev"
          envFrom:
            - secretRef:
                name: ts-sabnzbd
                namespace: media
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
    - metadata:
        name: downloads
        labels:
          app.kubernetes.io/name: downloads
      spec:
        resources:
          requests:
            storage: 1Ti
        storageClassName: hcloud-mass-storage
        accessModes:
          - ReadWriteOnce
    - metadata:
        name: incomplete-downloads
        labels:
          app.kubernetes.io/name: incomplete-downloads
      spec:
        resources:
          requests:
            storage: 500Gi
        storageClassName: hcloud-mass-storage
        accessModes:
          - ReadWriteOnce