apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: sonarr
    sidecar.istio.io/inject: "false"
  name: sonarr
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  serviceName: "sonarr"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      hostname: sonarr
      containers:
        - name: sonarr
          image: ghcr.io/linuxserver/sonarr:3.0.10.1567-ls200
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "750Mi"
          ports:
            - containerPort: 8989
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /tv
          env:
            - name: TZ
              value: "Europe/London"
            - name: DOCKER_MODS
              value: ghcr.io/behnh/docker-mod:main
            - name: TAILSCALE_STATE_DIR
              value: /config/tailscale
            - name: TAILSCALE_SERVE_MODE
              value: "http"
            - name: TAILSCALE_SERVE_PORT
              value: "8989"
            - name: TAILSCALE_HOSTNAME
              value: "sonarr"
            - name: TAILSCALE_CUSTOM_SERVER
              value: "https://vpn.behn.dev"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8989
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce