---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-db-postgres
  namespace: flux-system
spec:
  path: ./clusters/hetzner/apps/database/postgres/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 6h0s
  timeout: 30m