---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-vault
  namespace: flux-system
spec:
  path: ./clusters/hetzner/apps/openfaas/openfaas/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1
      kind: HelmRelease
      name: openfaas
      namespace: openfaas
  interval: 6h0s
  timeout: 30m
