apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  meshConfig:
    extensionProviders:
      - name: "authentik"
        envoyExtAuthzHttp:
          service: "authentik.security.svc.cluster.local"
          port: "9300"
          pathPrefix: "/outpost.goauthentik.io/auth/envoy"
          headersToDownstreamOnAllow:
            - cookie
          headersToUpstreamOnAllow:
            - set-cookie
            - x-authentik-*
          includeRequestHeadersInCheck:
            - cookie