apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  interval: 6h
  timeout: 30m
  dependsOn:
    - name: istio-istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system