---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-system
spec:
  interval: 6h
  timeout: 30m
  dependsOn:
    - name: istio-istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 200m
    autoscaling:
      minReplicas: 2
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: istio-ingress
    service:
      annotations:
        load-balancer.hetzner.cloud/name: "k8s-loadbalancer"
        load-balancer.hetzner.cloud/location: "fsn1"
        load-balancer.hetzner.cloud/use-private-ip: "true"
        load-balancer.hetzner.cloud/network-zone: eu-central
        load-balancer.hetzner.cloud/ipv6-disabled: "true"
        load-balancer.hetzner.cloud/health-check-port: "30733"
        load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
      externalTrafficPolicy: Cluster
      type: LoadBalancer
      ports:
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
