---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
  namespace: istio-system
spec:
  interval: 6h0s
  timeout: 30m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.23.0
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
  values:
    meshConfig:
      serviceSettings:
        - settings:
            clusterLocal: true
          hosts:
            - "kiali.monitoring.svc.cluster.local"
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"
      enableTracing: false
      enablePrometheusMerge: true
      extensionProviders:
        - envoyExtAuthzHttp:
            headersToDownstreamOnAllow:
              - cookie
            headersToUpstreamOnAllow:
              - set-cookie
              - x-authentik-*
            includeRequestHeadersInCheck:
              - cookie
            pathPrefix: /outpost.goauthentik.io/auth/envoy
            port: "9000"
            service: ak-outpost-authentik-embedded-outpost.security.svc.cluster.local
          name: authentik