---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 6h0s
  timeout: 30m
  chart:
    spec:
      chart: base
      version: 1.22.2
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
