apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password-charts
  namespace: flux-system
spec:
  interval: 30m
  # There's an issue atm with the 1password repo, so we need to use the raw pages url
  # https://github.com/1Password/connect-helm-charts/issues/153
  # url: https://1password.github.io/connect-helm-charts/
  url: https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
  timeout: 10m