---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://actions-runner-controller.github.io/actions-runner-controller
  timeout: 10m0s
