---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.goauthentik.io
  timeout: 10m0s
