---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.external-secrets.io
  timeout: 10m0s
