---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kiali.org/helm-charts
  timeout: 10m0s
