---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://pkgs.tailscale.com/helmcharts
  timeout: 10m0s