---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts-charts
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.truecharts.org/
  timeout: 10m0s
