apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: tfc-agent-pool
spec:
  organization: behnh
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: agent-pool
  agentTokens:
    - name: token
  agentDeployment:
    replicas: 3
    spec:
      containers:
        - name: tfc-agent
          image: "hashicorp/tfc-agent:latest"