---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tf-runners
  namespace: utilities
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 5m
  chart:
    spec:
      chart: hcp-terraform-operator
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
