---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tfc-operator
  namespace: utilities
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: kv/services/terraform
        property: runner-token