---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kiali
  namespace: monitoring
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: oidc-secret
      remoteRef:
        key: kv/services/kiali
        property: oidc_secret
