apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-smb-csi
  namespace: flux-system
  labels:
    substitutuion.flux.home.arps/enabled: "true"
spec:
  path: ./clusters/hetzner/apps/kube-system/smb-csi/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 6h0s
  retryInterval: 1m
  timeout: 10m0s