apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-config
  namespace: monitoring
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          common:
            storage:
              backend: s3
              s3:
                endpoint: s3.behn.dev
                secret_access_key: {{ .secrets.secret_key }}
                access_key_id: {{ .secrets.access_key }}

          blocks_storage:
            s3:
              bucket_name: mimir-blocks

          alertmanager_storage:
            s3:
              bucket_name: mimir-alertmanager

          ruler_storage:
            s3:
              bucket_name: mimir-ruler

          limits:
            max_label_names_per_series: 100
            max_global_series_per_user: 1500000
            max_global_series_per_metric: 200000
            ingestion_rate: 25000
            ruler_max_rules_per_rule_group: 500
            compactor_blocks_retention_period: 30d
            out_of_order_time_window: 1h

          minio:
            enable: false

          server:
            log_level: info
            log_format: json
  dataFrom:
    - extract:
        key: kv/services/mimir