apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-config
  namespace: monitoring
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          common:
            storage:
              backend: s3
              s3:
                endpoint: s3.behn.dev
                secret_access_key: {{ .secrets.secret_key }}
                access_key_id: {{ .secrets.access_key }}
  dataFrom:
    - extract:
        key: kv/services/mimir