apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mimir
  namespace: monitoring
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir