---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mimir
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  serviceName: mimir
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.9.1
          args:
            - --config.file=/etc/mimir/config.yaml
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "2"
              memory: 1Gi
            limits:
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: data
              mountPath: /data
      volumes:
        - name: config
          secret:
            secretName: mimir-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteOnce
