apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: golink-secret
  namespace: networking
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: kv/services/golink
        property: preauth_key