---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 1m0s
  chart:
    spec:
      chart: openfaas
      sourceRef:
        kind: HelmRepository
        name: openfaas
        namespace: flux-system
  values:
    generateBasicAuth: false
    istio:
      mtls: true
    gateway:
      directFunctions: true
      probeFunctions: true
