apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
metadata:
  name: descheduler-policy
  namespace: kube-system
profiles:
  - name: ProfileName
    pluginConfig:
    - name: "LowNodeUtilization"
      args:
        thresholds:
          "memory": 20
        targetThresholds:
          "memory": 60
    plugins:
      balance:
        enabled:
          - "LowNodeUtilization"