apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: storage
spec:
  resources:
    requests:
      storage: 1Ti
  storageClassName: hcloud-mass-storage
  accessModes:
    - ReadWriteOnce
