apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: storage
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - args:
            - server
            - --console-address=:9001
            - /storage
          env:
            - name: MINIO_DOMAIN
              value: s3.behn.dev,s3.hetzner.k8s.behn.dev
            - name: MINIO_BROWSER_REDIRECT_URL
              value: https://s3-console.behn.dev
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root_password
            # OIDC config
            - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
              value: https://id.behn.dev/application/o/userinfo/
            - name: MINIO_IDENTITY_OPENID_CONFIG_URL
              value: https://id.behn.dev/application/o/minio/.well-known/openid-configuration
            - name: MINIO_IDENTITY_OPENID_CLIENT_ID
              value: QeK4sLaowIn11fdmfPa6atsk2YW19ObOx4itVb0f
            - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: oidc_client_secret
            - name: MINIO_IDENTITY_OPENID_SCOPES
              value: openid,profile,email,minio
            - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
              value: Authentik
            # Monitoring
            - name: MINIO_PROMETHEUS_URL
              value: http://mimir.monitoring.svc.cluster.local
            - name: MINIO_PROMETHEUS_JOB_ID
              value: minio-job
          image: quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/live
              port: 9000
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 30
          name: minio
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
            - containerPort: 9001
              name: http-console
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /minio/health/ready
              port: 9000
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 30
          resources: {}
          volumeMounts:
            - mountPath: /storage
              subPath: minio/
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc