apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: storage
spec:
  resources:
    requests:
      storage: 100Gi
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
