apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: storage
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          rootUser: "{{ .root_user }}"
          rootPassword: "{{ .root_password }}"
  dataFrom:
    - extract:
        key: kv/services/minio