apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: storage
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: root_user
      remoteRef:
        key: kv/services/minio
        property: root_user
    - secretKey: root_password
      remoteRef:
        key: kv/services/minio
        property: root_password
    - secretKey: oidc_client_secret
      remoteRef:
        key: kv/services/minio
        property: oidc_client_secret