apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bsxy-secrets
  namespace: bluesky
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: BLUESKY_USERNAME
      remoteRef:
        key: kv/services/bluesky/bsxy
        property: bluesky_username
    - secretKey: BLUESKY_PASSWORD
      remoteRef:
        key: kv/services/bluesky/bsxy
        property: bluesky_password
    - secretKey: REDIS_URL
      remoteRef:
        key: kv/services/bluesky/bsxy
        property: redis_url