apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-external-secrets
  namespace: flux-system
spec:
  path: ./clusters/hetzner/apps/cert-manager/cert-manager/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  # healthChecks:
  #   - apiVersion: helm.toolkit.fluxcd.io/v1
  #     kind: HelmRelease
  #     name: external-secrets
  #     namespace: security
  interval: 6h0s
  timeout: 30m