apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-external-secrets
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: kube-system