apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
  namespace: kube-system
spec:
  provider:
    vault:
      server: "https://vault.svc.behn.dev"
      path: "kv"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: kube-system