apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secrets
  namespace: kube-system
spec:
  provider:
    vault:
      server: "https://vault.svc.behn.dev"
      path: "kv"
      auth:
        kubernetes:
          remoteNamespace: kube-system
          server:
            url: "https://kubernetes.default.svc"
            path: "kv"
            caProvider:
              type: ConfigMap
              name: kube-root-ca.crt
              key: ca.crt
              namespace: kube-system
          serviceAccount:
            name: external-secrets
            namespace: kube-system