apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-kv
spec:
  provider:
    vault:
      server: "https://vault.svc.behn.dev"
      path: "kv"
      auth:
        jwt:
          path: "k8s-hetzner"
          role: "external-secrets"
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: "external-secrets"
              namespace: "kube-system"
            audiences:
            - https://kubernetes.default.svc.cluster.local