apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-pullthrough
  namespace: utilities
spec:
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    template:
      data:
        REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
        REGISTRY_STORAGE_S3_BUCKET: registry-pullthrough
  dataFrom:
    - extract:
        key: kv/dockerhub