---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2023.10.7
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
  values:
    authentik:
      error_reporting:
        enabled: true
      email:
        from: "identity@services.behn.dev"
        host: "email-smtp.eu-west-2.amazonaws.com"
        port: 587
        use_tls: true
        use_ssl: false
      postgresql:
        host: postgresql.database.svc.cluster.local
        name: authentik
        username: authentik
      redis:
        host: redis-master.database.svc.cluster.local
    ingress:
      enabled: true
      ingressClassName: istio
      hosts:
        - host: id.behn.dev
          paths:
            - path: "/"
              pathType: Prefix
        - host: id.hetzner.k8s.behn.dev
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: behndev-global
          hosts:
            - id.behn.dev
            - id.hetzner.k8s.behn.dev
    redis:
      enabled: false
    prometheus:
      serviceMonitor:
        create: true
    resources:
      server:
        requests:
          cpu: 200m
        limits:
          cpu: "2"
