apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-secrets
  namespace: security
  labels:
    "app.kubernetes.io/managed-by": "Helm"
    "meta.helm.sh/release-name": "1password-connect"
    "meta.helm.sh/release-namespace": "security"
spec:
  itemPath: "vaults/infrastructure/items/authentik_secrets"