---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: security
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          postgresql:
            auth:
              password: "{{ .postgres_password }}"
          authentik:
            postgresql:
              password: "{{ .postgres_password }}"
            email:
              username: "{{ .email_username }}"
              password: "{{ .email_password }}"
            secret_key: "{{ .secret_key }}"
            redis:
              password: "{{ .redis_password }}"
  dataFrom:
    - extract:
        key: kv/services/authentik
