---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-security-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-db-redis
  path: ./clusters/hetzner/apps/security/authentik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 6h0s
  timeout: 30m
