---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-istio
  namespace: flux-system
  labels:
    substitutuion.flux.home.arps/enabled: "true"
spec:
  path: ./clusters/hetzner/apps/networking/istio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
