apiVersion: v1
kind: Service
metadata:
  name: nzbhydra2
  namespace: media
  labels:
    app.kubernetes.io/name: nzbhydra2
spec:
  selector:
    app.kubernetes.io/name: nzbhydra2
  ports:
  - targetPort: http
    port: 80
