apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: nzbhydra2
    sidecar.istio.io/inject: "false"
  name: nzbhydra2
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbhydra2
  serviceName: "nzbhydra2"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbhydra2
    spec:
      hostname: nzbhydra2
      containers:
        - name: nzbhydra2
          image: ghcr.io/linuxserver/nzbhydra2:v5.1.9-ls105
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "750Mi"
          ports:
            - containerPort: 5076
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /downloads
          env:
            - name: TZ
              value: "Europe/London"
            - name: DOCKER_MODS
              value: ghcr.io/behnh/docker-mod:main
            - name: TAILSCALE_STATE_DIR
              value: /config/tailscale
            - name: TAILSCALE_SERVE_MODE
              value: "http"
            - name: TAILSCALE_SERVE_PORT
              value: "5076"
            - name: TAILSCALE_HOSTNAME
              value: "nzbhydra2"
            - name: TAILSCALE_CUSTOM_SERVER
              value: "https://vpn.behn.dev"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce