---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
  namespace: tailscale
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          oauth:
            clientId: "{{ .client_id }}"
            clientSecret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: kv/services/tailscale
