---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 6h0m
  chart:
    spec:
      chart: postgresql
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  valuesFrom:
    - kind: Secret
      name: postgres-config
      valuesKey: values.yaml
  values:
    primary:
      service:
        annotations:
          tailscale.com/expose: "true"