---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-config
  namespace: database
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          global:
            storageClass: hcloud-volumes
          auth:
            enablePostgresUser: true
            postgresPassword: {{ .admin_password }}
            replicationPassword: {{ .replication_password }}
  dataFrom:
    - extract:
        key: kv/services/postgres
