apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: security
spec:
  acme:
    email: security@behn.dev
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: bshayhoe@gmail.com
          apiTokenSecretRef:
            name: cloudflare
            key: api-token