apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    logging {
      level = "info"
      format = "json"
    }
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://mimir.monitoring.svc.cluster.local/api/v1/push"
      }
    }
    loki.write "in_cluster" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local/loki/api/v1/push"
      }
    }
    discovery.kubernetes "k8s_pods" {
      role = "pod"
    }
    discovery.kubernetes "k8s_no_kube_system" {
      role = "pod"
      namespaces {
        names = ["analytics","database","media","monitoring","networking","security","storage","tailscale","utilities","flux-system","istio-system"]
      }
    }
    prometheus.scrape "k8s_pods" {
      targets = discovery.kubernetes.k8s_pods.targets
      forward_to = [prometheus.remote_write.mimir.receiver]
    }
    loki.source.kubernetes "k8s_pods" {
      targets = discovery.kubernetes.k8s_no_kube_system.targets
      forward_to = [loki.write.in_cluster.receiver]
    }