apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    sidecar.istio.io/inject: "false"
spec:
  timeout: 30m
  interval: 6h
  chart:
    spec:
      chart: alloy
      version: 0.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  upgrade:
    disableWait: true
  values:
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy