apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name workstation
  namespace: utilities
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      containers:
        - image: ghcr.io/behnh/workstation
          imagePullPolicy: IfNotPresent
          name: *name
          resources: {}
          volumeMounts:
            - name: host
              mountPath: /host
      volumes:
        - name: host
          hostPath:
            path: /