apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./grafana/kustomization.yaml
  - ./kiali/kustomization.yaml
  - ./mimir/kustomization.yaml
  - ./prometheus/kustomization.yaml