apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: behndev-global
  namespace: istio-system
spec:
  issuerRef:
    name: letsencrypt-prod
    group: cert-manager.io
    kind: ClusterIssuer
  secretName: behndev-global
  dnsNames:
    - '*.behn.dev'
    - '*.infra.behn.dev'
    - '*.svc.behn.dev'
    - '*.hetzner.k8s.behn.dev'