---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  timeout: 30m
  chart:
    spec:
      chart: cert-manager
      version: v1.13.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  interval: 6h
  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
