---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: hetzner-k8s
  secretRef:
    name: discord-webhook
  username: FluxBot
