---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name radarr
  namespace: media
  labels:
    app.kubernetes.io/name: *name
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  serviceName: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      hostname: *name
      containers:
        - name: *name
          image: ghcr.io/linuxserver/radarr:4.6.4.7568-ls180
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          ports:
            - containerPort: 7878
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: media-temp
              mountPath: /media-temp
          env:
            - name: TZ
              value: "Europe/London"
          livenessProbe:
            httpGet:
              path: /
              port: 7878
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: media-temp
          persistentVolumeClaim:
            claimName: media-temp-pvc
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: *name
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
