apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-secrets
  namespace: media
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: api-key
      remoteRef:
        key: kv/services/radarr
        property: api-key