apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blocky
  namespace: networking
spec:
  selector:
    matchLabels:
      app: blocky
  serviceName: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
      - name: blocky
        image: ghcr.io/0xerr0r/blocky:v0.21
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 4000
          name: http
          protocol: TCP
        env:
          - name: BLOCKY_CONFIG_FILE
            value: /config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: blocky
          items:
          - key: config.yaml
            path: config.yaml
