apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: networking
spec:
  selector:
    app: blocky
  ports:
  - port: 53
    targetPort: dns-udp
    protocol: UDP
  - port: 53
    targetPort: dns-tcp
    protocol: TCP
  - port: 4000
    targetPort: http
    protocol: TCP
