apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: networking
spec:
  selector:
    app: blocky
  ports:
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: dns-tcp
    protocol: TCP
  - name: http
    port: 4000
    targetPort: http
    protocol: TCP
