---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale-ui
  namespace: networking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale-ui
      app.kubernetes.io/instance: main
  template:
    metadata:
      labels:
        app.kubernetes.io/name: headscale-ui
        app.kubernetes.io/instance: main
    spec:
      securityContext:
          fsGroup: 1000
      containers:
        - image: ghcr.io/ifargle/headscale-webui:v0.6.2
          name: headscale-ui
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: HS_SERVER
              value: https://vpn.behn.dev
            - name: SCRIPT_NAME
              value: /ui
            - name: AUTH_TYPE
              value: oidc
            - name: OIDC_AUTH_URL
              value: https://id.behn.dev/application/o/headscale/.well-known/openid-configuration
          envFrom:
            - secretRef:
                name: headscale-ui-config
                namespace: networking
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/headscale
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "150m"
              memory: "300Mi"
      volumes:
        - name: config
          secret:
            secretName: headscale-config
        - name: data
          persistentVolumeClaim:
            claimName: headscale-ui
