apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: headscale
  namespace: istio-system
spec:
  hosts:
    - vpn.behn.dev
  gateways:
    - cluster-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: headscale.networking.svc.cluster.local
            port:
              number: 8080
    - match:
        - uri:
            prefix: /ui
      route:
        - destination:
            host: headscale-ui.networking.svc.cluster.local
            port:
              number: 8080