apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 6h0s
  timeout: 30m
  chart:
    spec:
      chart: hcloud-cloud-controller-manager
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: hetzner-charts
        namespace: flux-system
  values:
    networking:
      enabled: true