---
apiVersion: v1
kind: Service
metadata:
  name: &name sonarr-exporter
  namespace: media
  labels: &app_labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  clusterIP: None
  selector:
    <<: *app_labels
  ports:
    - name: monitoring
      port: 9707
