---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: &name sonarr-exporter
  namespace: media
  labels: &app_labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.sonarr-exporter: semver:~v0.1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      <<: *app_labels
  template:
    metadata:
      labels:
        <<: *app_labels
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: *name
          image: ghcr.io/onedr0p/exportarr:v1.6.2
          imagePullPolicy: IfNotPresent
          args:
            - sonarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://sonarr"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sonarr-secrets
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
