apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonflydb
  namespace: database
spec:
  interval: 6h0m
  chart:
    spec:
      chart: dragonfly
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: dragonflydb-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    storage:
      enabled: true
      requests: 128Mi
    extraArgs:
      - --dbfilename=dump.rdb
      - --save_schedule=*:*
    podSecurityContext:
      fsGroup: 2000
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    serviceMonitor:
      enabled: true