apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner
  namespace: utilities
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 6h
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.5.2
      sourceRef:
        kind: HelmRepository
        name: arc-charts
        namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    fullNameOverride: gha-runner-scale-set-controller