apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actions-runner
  namespace: utilities
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 6h
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.7
      sourceRef:
        kind: HelmRepository
        name: arc-charts
        namespace: flux-system

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    fullnameOverride: actions-runner-controller
    image:
      repository: ghcr.io/actions-runner-controller/actions-runner-controller
      tag: v0.27.5-52fc819
    authSecret:
      create: false
      name: arc-secrets
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    githubWebhookServer:
      enabled: true
      logFormat: json
      fullnameOverride: arc-github-webhooks

    metrics:
      serviceMonitor:
        enabled: false
      port: 8080
      proxy:
        enabled: false
    actionsMetrics:
      serviceMonitor:
        enabled: false
      port: 8080
      proxy:
        enabled: false
    actionsMetricsServer:
      enabled: false

    resources:
      requests:
        cpu: 10m
        memory: 250M
      limits:
        memory: 450M
