---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-secrets
  namespace: utilities
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
    - secretKey: github_token
      remoteRef:
        key: kv/services/arc
        property: github_token