---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name sabnzbd-exporter
  namespace: media
  labels: &app_labels
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  selector:
    matchLabels:
      <<: *app_labels
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
