---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name sabnzbd
  namespace: media
  labels:
    app.kubernetes.io/name: *name
    sidecar.istio.io/inject: "false"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  serviceName: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      hostname: *name
      containers:
        - name: *name
          image: ghcr.io/linuxserver/sabnzbd:4.2.1
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "750Mi"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: incomplete-downloads
              mountPath: /incomplete-downloads
          env:
            - name: DOCKER_MODS
              value: ghcr.io/behnh/docker-mod:main
            - name: TAILSCALE_STATE_DIR
              value: /config/tailscale
            - name: TAILSCALE_SERVE_MODE
              value: "http"
            - name: TAILSCALE_SERVE_PORT
              value: "8080"
            - name: TAILSCALE_HOSTNAME
              value: *name
            - name: TAILSCALE_CUSTOM_SERVER
              value: "https://vpn.behn.dev"
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: media-pvc
        - name: incomplete-downloads
          persistentVolumeClaim:
            claimName: media-temp-pvc
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app.kubernetes.io/name: config
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
