---
apiVersion: v1
kind: Service
metadata:
  name: &name sabnzbd
  namespace: media
  labels:
    app.kubernetes.io/name: *name
spec:
  selector:
    app.kubernetes.io/name: *name
  ports:
    - targetPort: http
      port: 80
