apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
  - targetPort: http
    port: 80
