apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-system-external-secrets
  namespace: flux-system
spec:
  path: ./clusters/hetzner/apps/kube-system/external-secrets/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1
      kind: HelmRelease
      name: external-secrets
      namespace: kube-system
  interval: 6h0s
  timeout: 30m
