---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
    - prometheus.infra.behn.dev
  http:
    - route:
        - destination:
            port:
              number: 9090
            host: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
