---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: se-prometheus
  namespace: istio-system
spec:
  hosts:
    - prometheus.infra.behn.dev
  ports:
    - number: 9090
      name: http
      protocol: http
  location: MESH_INTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: istio-system
spec:
  hosts:
    - prometheus.infra.behn.dev
  http:
    - route:
        - destination:
            port:
              number: 9090
            host: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
