---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-scrape-configs
  namespace: monitoring
spec:
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  target:
    template:
      data:
        jobs.yaml: |
          - job_name: "istiod"
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                  - istio-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring

          - job_name: 'envoy-stats'
            metrics_path: /stats/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'

          - job_name: minio-job
            bearer_token: {{ .minio_bearer_token }}
            metrics_path: /minio/v2/metrics/cluster
            scheme: https
            static_configs:
              - targets: [s3.behn.dev]

          - job_name: felix_metrics
            scrape_interval: 5s
            scheme: http
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: felix-metrics-svc
              replacement: $1
              action: keep

          - job_name: typha_metrics
            scrape_interval: 5s
            scheme: http
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: typha-metrics-svc
              replacement: $1
              action: keep
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              regex: calico-typha
              action: drop

          - job_name: kube_controllers_metrics
            scrape_interval: 5s
            scheme: http
            kubernetes_sd_configs:
            - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: calico-kube-controllers-metrics
              replacement: $1
              action: keep

          - job_name: "sonarr-exporter"
            static_configs:
              - targets: ["sonarr-exporter.media.svc.cluster.local:9707"]

          - job_name: "radarr-exporter"
            static_configs:
              - targets: ["radarr-exporter.media.svc.cluster.local:9707"]

  dataFrom:
    - extract:
        key: kv/services/prometheus-scraping
